//
//  MainRouter.swift
//  CleanSwiftApiCars
//
//  Created by André Brilho on 12/09/19.
//  Copyright (c) 2019 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainRoutingLogic {
    func routeToDetail()
}

protocol MainDataPassing {
    var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing
{
    
    weak var viewController: MainViewController?
    var dataStore: MainDataStore?
    
    func routeToDetail() {
        let storyBoard = UIStoryboard(name: "Main", bundle:nil)
        let detail = storyBoard.instantiateViewController(withIdentifier: "detailVC")
        var destinationDS = (detail as! DetailViewController).router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        viewController?.navigationController?.pushViewController(detail, animated: true)
    }
    
    func passDataToSomewhere(source: MainDataStore, destination: inout DetailDataStore) {
        destination.selectedCar = source.selectedCar
    }
}
