//
//  MainModels.swift
//  CleanSwiftApiCars
//
//  Created by André Brilho on 12/09/19.
//  Copyright (c) 2019 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main {
    
    struct Carro:Decodable{
        var nome:String
        var desc:String
        var url_foto:String
    }
    
    struct Carros:Decodable {
        var carro:[Carro]
    }
    
    struct CarrosResponse: Decodable {
        var carros:Carros
    }
}
