//
//  MainPresenter.swift
//  CleanSwiftApiCars
//
//  Created by André Brilho on 12/09/19.
//  Copyright (c) 2019 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func reloadTable()
    func routeToDetail()
}

class MainPresenter: MainPresentationLogic {
    
  weak var viewController: MainDisplayLogic?
    
    func reloadTable() {
        viewController?.reloadTable()
    }
    
    func routeToDetail() {
        viewController?.routeToDetail()
    }

}
