//
//  DetailInteractor.swift
//  CleanSwiftApiCars
//
//  Created by André Brilho on 12/09/19.
//  Copyright (c) 2019 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic {
    func load()
}

protocol DetailDataStore {
    var selectedCar: Main.Carro? { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore {
    var presenter: DetailPresentationLogic?
    var worker: DetailWorker?
    var selectedCar: Main.Carro?
    
    init(worker:DetailWorker = DetailWorker()) {
        self.worker = worker
    }
    
    func load(){
        presenter?.showDesc(desc: selectedCar?.desc ?? "")
        presenter?.showName(name: selectedCar?.nome ?? "")
    }
}
