//
//  DetailPresenter.swift
//  CleanSwiftApiCars
//
//  Created by André Brilho on 12/09/19.
//  Copyright (c) 2019 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic {
    func showName(name:String)
    func showDesc(desc:String)
}

class DetailPresenter: DetailPresentationLogic {
    
  weak var viewController: DetailDisplayLogic?
    
    func showName(name: String) {
        viewController?.showName(name: name)
    }
    
    func showDesc(desc: String) {
        viewController?.showDesc(desc: desc)
    }
  
}
